apiVersion: apps/v1
kind: Deployment
metadata:
  name: teledoist-api-deployment
  labels:
    app: teledoist-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teledoist-api
  template:
    metadata:
      labels:
        app: teledoist-api
    spec:
      containers:
        - name: teledoist-api
          image: paulbuzakov/teledoist-api:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: teledoist-api-service
spec:
  selector:
    app: teledoist-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
