apiVersion: apps/v1
kind: Deployment
metadata:
  name: teledoist-api
  labels:
    app: teledoist-api
spec:
  selector:
    matchLabels:
      app: teledoist-api
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: teledoist-api
      labels:
        app: teledoist-api
    spec:
      containers:
        - name: teledoist-api
          image: paulbuzakov/teledoist-api:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - "-c"
            - "sleep 60m"
          ports:
            - containerPort: 80
              name: teledoist-api
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: teledoist-api
#spec:
#  selector:
#    app: teledoist-api
#  type: ClusterIP
#  ports:
#    - name: teledoist-api
#      protocol: TCP
#port: 80
#targetPort: 80

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: teledoist-api
#annotations:
#  cert-manager.io/cluster-issuer: lets-encrypt
#spec:
#  tls:
#  - hosts:
#        - teledoist.paulbuzakov.com
#      secretName: teledoist-api-ingress-tls
#rules:
#    - host: teledoist.paulbuzakov.com
#      http:
#  paths:
#          - backend:
#              service:
#                name: teledoist-api
#                port:
#                  number: 80
#            path: /api
#            pathType: Exact
