apiVersion: apps/v1
kind: Deployment
metadata:
  name: teledoist-api-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: teledoist-api
  template:
    metadata:
      name: my-teledoist-api
      labels:
        env: prod
        app: teledoist-api
    spec:
      containers:
        - name: teledoist-api
          image: paulbuzakov/teledoist-api:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

---

apiVersion: v1
kind: Service
metadata:
  name: teledoist-api-lb-service
spec:
  selector:
    app: teledoist-api
  type: ClusterIP
  ports:
    - name: teledoist-api-port
      protocol: TCP
      port: 35000
      targetPort: 80
      nodePort: 35000
  type: LoadBalancer

---

